### ISSUE TITLE
problema upload imgbly

### ISSUE THREAD

**Issue by SiNaPsEr0x** [c137ricksanchez/automatic-releaser#25]
salve.. quando carica il file su imgbly rimane bloccato e non prosegue..
ps: non da errori.. semplicemente rimane freezato
 al momento ho dovuto fixare cambiando il formato in jpg ... attendo fix grazie

**Comment by xm4rcell0x** [comment]
Anche io stesso problema con imgBB e i formati png per i file 4K. 
Il caricamento alternativo su imgbly fallisce .

Allego cioè che mi viene restituito:


6. Caricamento delle immagini su ImgBB...
Si è verificato un errore durante il caricamento delle immagini su ImgBB
errore ImgBB nel tentativo di caricare l'immagine:  \Users\Marcello\Documents\File make release\Ex.Machina.2014.UHD.BluRay.HDR.2160p.DTS.AAC.iTA.DDP7.1.DD5.1.ENG.Subs.x264-BJL_files\00.05.30.png   -->   File too big - max 32 MB
Tentativo di caricamento alternativo su https://imgbly.com/
Avvio caricamento con ImgBly di: 00.05.30.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Marcello\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1967, in call
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Marcello\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\Marcello\makerelease\gui.py", line 121, in make_release
    releaser.make_release()
  File "C:\Users\Marcello\makerelease\src\makerelease\app.py", line 194, in make_release
    uploaded_imgs = [images.upload_to_imgbb(img) for img in screenshots]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marcello\makerelease\src\makerelease\images.py", line 80, in upload_to_imgbb
    return imgbb.upload_image(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marcello\makerelease\src\makerelease\api\imgbb.py", line 37, in upload_image
    imgbly_upload = imgbly.upload_image(path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marcello\makerelease\src\makerelease\api\imgbly.py", line 29, in upload_image
    full_url = f"{BASE_URL}ib/{full_res['data']['id']}.png"
                               ~~~~~~~~^^^^^^^^
KeyError: 'data'
